# Deep Thinking Engine - System Configuration

system:
  log_level: INFO
  max_concurrent_agents: 10
  default_timeout: 300
  enable_caching: true
  cache_ttl: 3600
  debug_mode: false

agents:
  default_temperature: 0.7
  default_max_retries: 3
  quality_threshold: 0.8
  enable_parallel_execution: true
  
  # Agent-specific configurations
  decomposer:
    max_sub_questions: 5
    complexity_assessment: true
    
  evidence_seeker:
    max_sources_per_query: 10
    source_diversity_requirement: true
    credibility_threshold: 0.6
    
  critic:
    paul_elder_standards: 
      - accuracy
      - precision
      - relevance
      - logic
      - breadth
      - depth
      - significance
      - fairness
      - clarity
    fallacy_detection: true
    
  bias_buster:
    comprehensive_check: true
    bias_types:
      - confirmation_bias
      - anchoring
      - availability_heuristic
      - representativeness
      - overconfidence
      
  innovator:
    methods:
      - SCAMPER
      - TRIZ
      - lateral_thinking
    novelty_threshold: 0.7
    
  reflector:
    socratic_questioning: true
    metacognitive_depth: deep

search:
  max_results_per_query: 10
  search_timeout: 30
  enable_source_diversity: true
  preferred_sources:
    - academic
    - government
    - news
  
database:
  path: "data/thinking_sessions.db"
  enable_encryption: true
  backup_interval: 3600
  
cache:
  evidence_ttl: 3600
  evaluation_cache_size: 500
  debate_cache_size: 100

export:
  # Base directory for exported files
  # Supports environment variable expansion (${VAR} or ${VAR:-default})
  base_directory: "${DEEP_THINKING_EXPORT_DIR:-~/.deep-thinking/exports}"
  
  # File organization options  
  organize_by_date: false  # Creates YYYY-MM-DD subdirectories
  max_file_count: 100      # Auto-cleanup old files (0 = disabled)
  
  # File naming pattern
  file_naming:
    # Available patterns:
    # - "{timestamp}_{topic}.md" (recommended: concise, chronological)
    # - "{topic}_{timestamp}.md" (topic-first ordering)
    # - "{session_id_short}_{topic}.md" (session ID prefix, 8 chars)
    # - "{timestamp}.md" (timestamp only, minimal)
    pattern: "{topic}_{timestamp}.md"
    sanitize_topic: true    # Remove special characters from topic
    max_topic_length: 20    # Truncate long topics (recommend Host provides concise title)
    include_session_id: false # Session ID is unique but creates very long filenames
    
  # Directory validation
  warn_git_pollution: true  # Warn if export dir is inside git repo
  create_missing_dirs: true # Auto-create export directories